# Generated by Django 2.0.5 on 2018-10-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontact',
            name='contact_type',
            field=models.CharField(max_length=10),
        ),
    ]
